name: Dev Branch CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version

      - name: Install Dependencies
        run: npm ci # Ensures a clean and consistent install

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build # Only include this if your project requires a build step
